### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED in colab 

### ISSUE THREAD

**Issue by AnselmeGildas** [caiyuanhao1998/MST-plus-plus#25]
`load model from /content/mst_plus_plus.pth
Reconstructing /content/MST-plus-plus/predict_code/demo/ARAD_1K_0912.jpg
Traceback (most recent call last):
  File "/content/MST-plus-plus/predict_code/test.py", line 84, in <module>
    main()
  File "/content/MST-plus-plus/predict_code/test.py", line 28, in main
    test(model, opt.rgb_path, opt.outf)
  File "/content/MST-plus-plus/predict_code/test.py", line 40, in test
    result = forward_ensemble(rgb, model, opt.ensemble_mode)
  File "/content/MST-plus-plus/predict_code/test.py", line 74, in forward_ensemble
    data = forward_func(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/MST-plus-plus/predict_code/architecture/MST_Plus_Plus.py", line 289, in forward
    x = self.conv_in(x)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

Hi,
I find your project very interesting and plan to adapt it for the provision of less expensive multispectral images for farmers in developing countries based on RGB images from recreational drones.
Thank you for sharing resources.

We come to my problem. I tried to use the model on colab to make the demo not having a graphics card on my machine but I ran into this problem. Is there a way to set it to run on colab?

**Comment by caiyuanhao1998** [comment]
Hi, 

Thanks for your interest. We have not tried to run our code on the colab. The issue "cuDNN error: CUDNN_STATUS_NOT_INITIALIZED" prompts because the conda environment is not correct. I suggest you set up the conda environment as introduced in our repo. Wish this help you.

Best
